name: minishell CI

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  issues: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.13

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libreadline-dev

      - name: Build
        run: make

      - name: Run tests
        run: |
          chmod +x .github/tests/test_minishell.sh
          .github/tests/test_minishell.sh
